### ISSUE TITLE
Week 3 코테 스터디 설명 문제 리스트

### ISSUE THREAD

**Issue by Sabro98** [alps-jbnu/22ALPStudy#115]
@copyrat90 @qhur135 @Sabro98 

자신이 내일 어떤 문제를 설명할건지 간략하게 써주세요~

여기 적힌 문제들은 최소 한번쯤은 생각해보고 스터디 시간에 공유하는게 좋아보이네요

**Comment by Sabro98** [comment]
[데이터 체커](https://www.acmicpc.net/problem/22942)
스택 발상 + 다른 풀이 (세그트리 사용) 설명 예정, [자료](https://github.com/alps-jbnu/22ALPStudy/tree/master/Coding_Interview/Code/Sabro98/Queue_Stack#%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%B2%B4%EC%BB%A4)

**Comment by copyrat90** [comment]
[22866번: 탑 보기](https://www.acmicpc.net/problem/22866) : [스택 아이디어, 시간복잡도 증명 등.](https://velog.io/@copyrat90/BOJ-22866)

**Comment by jihyeonhur** [comment]
[다리를 지나는 트럭](https://programmers.co.kr/learn/courses/30/lessons/42583) 
[아이디어](https://github.com/alps-jbnu/22ALPStudy/blob/master/Coding_Interview/Code/qhur135/Queue_Stack/README.md), 시간복잡도 설명 예정
