### ISSUE TITLE
4/4 Week4 자료구조 공유할 문제 조사

### ISSUE THREAD

**Issue by jys-jeong** [alps-jbnu/22ALPStudy#116]
효율적인 스터디 진행을 위해 필요한 내용을 조사하려 합니다.

4/3 21:00까지 풀어보시고, 그 이후부터 올려주시면 되겠습니다.
'풀어보았지만 끝까지 해결하지 못한 문제' 를 적어주시고, 이후 본인의 풀이 방법을 공유하고자 하는 분은 '좋아요'를 남겨주시면 되겠습니다.

@AFpine @Zoe305 @tlstmdgjs @IMAYOUNG @rkdbq

**Comment by AFpine** [comment]
16933 벽 부수고 이동하기 3

**Comment by rkdbq** [comment]
2206: 벽 부수고 이동하기
5214: 환승

**Comment by jys-jeong** [comment]
2617 구슬찾기
