### ISSUE TITLE
스터디 관련 질문 있습니다

### ISSUE THREAD

**Issue by joonas-yoon** [alps-jbnu/22ALPStudy#131]
안녕하세요 졸업생 윤준하라고 합니다 반가워요.

작은 이벤트를 하나 열까하는데요, 혹시 지금 비대면으로 진행되고 있나요?

**Comment by AFpine** [comment]
2학년 자료구조 스터디와 1학년 신입생 C언어 멘토링은 팀을 나누어 대면으로 진행하고 있습니다

**Comment by Sabro98** [comment]
안녕하세요

스터디는

1학년 C언어 스터디
2학년 자료구조 스터디
3/4학년 코테, 대회 스터디

모두 대면으로 진행중입니다

**Comment by joonas-yoon** [comment]
오 그렇군요 답변 감사합니다 ㅎㅎ
