### ISSUE TITLE
4/6 자료구조 B 토의 문제 조사

### ISSUE THREAD

**Issue by bootkorea** [alps-jbnu/22ALPStudy#135]
효율적인 스터디 진행을 위해 필요한 내용을 조사하겠습니다.

4/5 18:00까지 풀어보시고, 그 이후부터 올려주시면 되겠습니다.

스터디 진행 중 공지한대로
1. 해결하였지만, 어려움을 겪었던 문제
2. 끝까지 해결하지 못하여 그룹원과 토의하고 싶은 문제
3. 이외 스터디 시간에 다루면 좋을 것이라 여겨지는 문제
를 댓글로 남겨주시면 됩니다.

댓글로 남겨진 문제는 스터디 시간에 필수적으로 다루어지므로 가능하다면 무조건적으로 해결하는 편을 권장합니다.

@alphasobs @tjdeo1102 @zs0057 @vuswltmd @JC-arl

**Comment by zs0057** [comment]
5567 결혼식 
BFS와 비교하여 메모리 부분에서 짚고 가고 싶은 부분이 있습니다.

**Comment by bootkorea** [comment]
11403 회장 뽑기
'플로이드-와샬'의 개념에 대해 짚어보면 좋을 것 같습니다

**Comment by bootkorea** [comment]
5214 환승
어려운 문제가 아닌데도 난이도가 높았던 이유와, 문제를 풀면서 도입해야 할 개념에 대해 이야기해보고자 합니다

**Comment by Sabro98** [comment]
개념 관련해서 공유하면 좋을 것 같은 부분들은 여기에 추가적으로 남겨주세요~
