### ISSUE TITLE
Week 4 코테 스터디 설명할 문제들

### ISSUE THREAD

**Issue by Sabro98** [alps-jbnu/22ALPStudy#151]
@copyrat90 @qhur135 @Sabro98 

자신이 내일 어떤 문제를 설명할건지 간략하게 써주세요~

여기 적힌 문제들은 최소 한번쯤은 생각해보고 스터디 시간에 공유하는게 좋아보이네요

**Comment by copyrat90** [comment]
12764번: 싸지방에 간 준하
[본인 작성 블로그 설명글](https://velog.io/@copyrat90/BOJ-12764)

**Comment by jihyeonhur** [comment]
[21939번: 문제 추천 시스템 Version 1](https://www.acmicpc.net/problem/21939), 우선순위큐 설명 예정

**Comment by Sabro98** [comment]
[N으로 만들기](https://noj.am/17255)

아이디어 설명
