### ISSUE TITLE
5/16 자료구조 A 스터디 간 다룰 문제

### ISSUE THREAD

**Issue by bootkorea** [alps-jbnu/22ALPStudy#181]
효율적인 스터디 진행을 위해 필요한 내용을 조사하겠습니다.

5/15 18:00까지 풀어보면서, 본인이 생각하기에 아래 조건에 해당하는 문제를 올려주시면 되겠습니다.

스터디 진행 중 공지한대로

해결하였지만, 어려움을 겪었던 문제
끝까지 해결하지 못하여 그룹원과 토의하고 싶은 문제
이외 스터디 시간에 다루면 좋을 것이라 여겨지는 문제

를 댓글로 남겨주시면 됩니다.

@AFpine @Zoe305 @tlstmdgjs @IMAYOUNG @rkdbq @jys-jeong

**Comment by AFpine** [comment]
2533 사회망 서비스(SNS)
다이나믹 프로그래밍에 대해 토의하고 싶습니다

**Comment by rkdbq** [comment]
2533 사회망 서비스(SNS)
