### ISSUE TITLE
5/23 자료구조 A 스터디 토의 문제

### ISSUE THREAD

**Issue by bootkorea** [alps-jbnu/22ALPStudy#195]
<트리, BST>

5/22 18:00 이후, 본인이 생각하기에 아래 조건에 해당하는 문제를 올려주시면 되겠습니다.

스터디 진행 중 공지한대로

해결하였지만, 어려움을 겪었던 문제
끝까지 해결하지 못하여 그룹원과 토의하고 싶은 문제
이외 스터디 시간에 다루면 좋을 것이라 여겨지는 문제

를 댓글로 남겨주시면 됩니다.

@AFpine @Zoe305 @tlstmdgjs @IMAYOUNG @rkdbq @jys-jeong

**Comment by rkdbq** [comment]
**끝까지 해결하지 못하여 그룹원과 토의하고 싶은 문제**

-   23326 홍익 투어리스트
-   19700 수업

**Comment by AFpine** [comment]
19700 수업
아이디어가 중요한 문제
