### ISSUE TITLE
5/30 자료구조 A 토의 문제

### ISSUE THREAD

**Issue by bootkorea** [alps-jbnu/22ALPStudy#213]
<Heap => Priority_queue>

5/29 18:00 이후, 본인이 생각하기에 아래 조건에 해당하는 문제를 올려주시면 되겠습니다.

스터디 진행 중 공지한대로

해결하였지만, 어려움을 겪었던 문제
끝까지 해결하지 못하여 그룹원과 토의하고 싶은 문제
이외 스터디 시간에 다루면 좋을 것이라 여겨지는 문제

를 댓글로 남겨주시면 됩니다.

@AFpine @Zoe305 @tlstmdgjs @IMAYOUNG @rkdbq @jys-jeong

**Comment by AFpine** [comment]
1781 컵라면
직관과는 조금 다르게 생각해야 하는 문제
어려웠습니다
