### ISSUE TITLE
저장소 및 향후계획 정리

### ISSUE THREAD

**Issue by jinhongjung** [alps-jbnu/22ALPStudy#223]
안녕하세요. 

모두들 한 학기 동안 학업에 스터디를 병행하느라 고생 많으셨습니다 👏

지난 미팅때 논의 했던 내용을 간략하게 정리하고 다같이 공유하면 좋을 것 같습니다. 학기 말에 바쁘겠지만 조금의 에너지를 투입해서 정리를 하고 넘어가면 여름방학, 2학기를 보내는데 많은 도움이 될거에요. 6월 30일까지 정리하고 산뜻하게 7월을 맞이하는게 어떨까요?!

스터디 관련해서 매니저분 (@bootkorea, @jys-jeong, @AFpine, @Santam) 들께서 주로 정리해주시면 좋을 것 같고요 회장님 (@Sabro98)께서는 좀 더 큰 틀에서 조율을 해주면 좋을 것 같아요. 스터디 참여 했던 멤버 분들도 스터디를 진행하면서 좋았던 점, 힘들었던 점, 개선점 등을 적극적으로 게시해주시면 향후 스터디 계획에 반영에 도움이 될 것 같습니다 (그래야 다음 스터디도 효과적으로 할 수 있고 여러분들의 후배들에게도 도움이 됩니다. ALPS 멤버들은 서로 도움을 받기도 하고 도움을 줄 수도 있는 그런 멤버였으면 좋겠습니다!)

우선 여기 issue에서 안건별로 정리하고 추가적으로 논의가 필요한 부분은 여기에서 같이 논의하면 좋겠습니다. 지난 번에 이야기 나왔던 사항을 안건 단위로 정리해 보았습니다. 

1. 2학년 대상 [여름방학 - 2학기] 알고리즘 스터디 계획 (1학기 자료구조 스터디 피드백 반영하여)
2. 신입생 대상 [여름방학 - 2학기] 자료구조 스터디 계획
3. 프로그래밍 대회/해커톤 등 참여 (특히 3/4학년)
4. 저장소를 (매 스터디마다 새로 파지 않고) 지속적으로 운영할 수 있는 방안 생각하기 
5. ICPC 대회 준비팀도 정리/공유겸 README 수준으로 공부 자료와 준비 history를 한 번 정리하고 꾸준히 업데이트하는 것은 어떨까요?

@joonas-yoon 선배님께서도 (3번 관련해서) 의견 주면 정말 고맙겠습니다 👏

**Comment by Sabro98** [comment]
일단 4, 5번에 관해서는 오늘 중으로 repo에 반영 계획입니다.

1, 2, 3번에 대해서도 정리 내용을 Readme를 통해 곧 올릴 예정입니다.

**Comment by joonas-yoon** [comment]
혹시 BOJ 그룹 아직도 쓰고 있나요?

**Comment by Sabro98** [comment]
아, BOJ 그룹 사용하지 않았습니다.

**Comment by joonas-yoon** [comment]
https://www.acmicpc.net/group/1102

2018년까지 사용했던 그룹으로 기억하구요, 문제집/게시판/파일에 자료가 남아있을거라 참고하면 좋겠습니다~

멤버로 추가가 필요한 사람 + 관리자 권한이 필요한 사람은 boj handle 적어주시면 추가하도록 할게요

**Comment by joonas-yoon** [comment]
@jinhongjung 구글 드라이브에도 공유 폴더로 있을텐데요

특히 secret 파일은 공유를 다시 해야할 듯 합니다. 물론 시간이 지나서 많이 의미없는 정보가 있겠지만요

**Comment by Sabro98** [comment]
> https://www.acmicpc.net/group/1102
> 
> 2018년까지 사용했던 그룹으로 기억하구요, 문제집/게시판/파일에 자료가 남아있을거라 참고하면 좋겠습니다~
> 
> 멤버로 추가가 필요한 사람 + 관리자 권한이 필요한 사람은 boj handle 적어주시면 추가하도록 할게요

오 감사합니다!
살펴봐야겠네요

일단  inhyuk05, alphasobs 이렇게 2명 부탁드립니다.

**Comment by joonas-yoon** [comment]
@Sabro98 추가했습니다~ 다시보니까 2019년까지 썼네요

**Comment by Sabro98** [comment]
스터디 폴더 구조 및 Readme를 더 나은 방향으로 수정했습니다.

구조가 많이 바뀌었으니 기존 자신의 repo를 삭제하고 다시 fork하는 것을 추천드립니다
(Settings -> Delete this repository 실행 후 다시 Fork)

구조가 다른 상태로 PR 요청을 하면 곤란한 상황이 발생해요 😅

---
@AFpine @rkdbq @jys-jeong @IMAYOUNG @tlstmdgjs @Zoe305 @bootkorea @vuswltmd @JC-arl @zs0057 @choi-w-s
