### ISSUE TITLE
저장소 정리

### ISSUE THREAD

**Issue by jinhongjung** [alps-jbnu/22ALPStudy#42]
학생들 스터디 진행 사항을 확인하러 왔는데 현재 저장소에 있는 내용으로는 확인이 쉽지 않네요. 정리가 필요해보이는데 우선 아래 내용을 진행해줄 수 있을까요? @Sabro98 

- 레포에 굳이 필요 없는 파일이나 자료는 삭제해주세요. 
- 레포 root에는 Coding_Interview, Data_Strcuture, Programming_Contest 폴더로만 구성하고 각 스터디에 맞춰서 자료를 정리하면 좋을 것 같습니다.
- 각 스터디 별로 README를 두고 운영방식, 공부계획, 자료 링크를 포함하여 조원별로 계획 달성 여부나 진도를 쉽게 확인 할 수 있도록 정리해줄 수 있을까요? (각 스터디 매니저가 봉사해주면 고맙겠습니다).

**Comment by joonas-yoon** [comment]
참고로 org가 있으니 https://github.com/alps-jbnu 여기를 써도 됩니다

**Comment by jinhongjung** [comment]
@joonas-yoon 사실 그것도 같이 논의 하긴 했었는데요, 다들 바쁘시니 ㅠㅠ 시간 부족하면 스터디 종료 후에 이관하는 형태로 가도 괜찮을것 같아요~~

**Comment by jinhongjung** [comment]
@Sabro98 각 스터디 readme에 매니저 분들 성함도 같이 기재 부탁드리겠습니다~

**Comment by Sabro98** [comment]
@jinhongjung 넵 알겠습니다~

한 1~2주 운영해보니 alps-jbnu 계정에 만들어서 하는게 훨씬 나을거라는 생각이 들어서.. 이번 주말 사용해서 해버리는것도 좋다고 생각합니다.

현재 운영중인 이 리포지토리 상태 그대로 위치만 옮기는 (또는 미러링할) 방법이 있을까요?

찾아보니 git clone -mirror 라는 명령어를 써서 할 수 있다고 하는데.. 
실행했을 때 fork해간 사람들에게 어떤 영향을 주는지 잘 모르겠네요

이 repo를 repo_original, 새로운 repo를 repo_new 라고 할 때, 
1. 이미 fork해간 사람들 모두 repo_original delete 후 새로운 repo_new fork -> 제일 간단할것같음
2. delete할 필요 없이 repo_original에 update 되는게 repo_new 에도 적용이 된다면 그대로 사용

**Comment by jinhongjung** [comment]
ownership을 특정 organization으로 transfer를 할 수 있어서 그걸 생각하고 있었는데요 ([link](https://docs.github.com/en/enterprise-server@3.1/repositories/creating-and-managing-repositories/transferring-a-repository))

이렇게 여러 fork가 된 상태에서 ownership을 변경 했을 때 그게 유지 될지는 안해봐서 스터디 다 종료되고 transfer 하는게 덜 문제되지 않을까 생각을 해보았습니다

아니면 간단하게 테스트용 저장소를 만들고 비슷하게 fork를 한다음에 ownership을 변경해보았을 때 어떻게 되는지 체크해 볼 수도 있을것 같아요 (private fork는 이전이 안된다고 하니 public fork는 될지도 모르겠네요 - If the transferred repository has any forks, then those forks will remain associated with the repository after the transfer is complete).

**Comment by jinhongjung** [comment]
굳이 상황을 복잡하게 만들 필요 없이 아직 1~2주 밖에 안됐으니 alps-jbnu에 새로운 저장소 파고 기존꺼 내용 copy해서 넣는것도 방법이구요~

**Comment by jinhongjung** [comment]
굳이 상황을 복잡하게 만들 필요 없이 아직 몇 주밖에 안됐으니 alps-jbnu에 새로운 저장소 파고 기존꺼 내용 copy해서 넣는것도 방법이구요~

**Comment by joonas-yoon** [comment]
> ownership을 특정 organization으로 transfer를 할 수 있어서 그걸 생각하고 있었는데요 ([link](https://docs.github.com/en/enterprise-server@3.1/repositories/creating-and-managing-repositories/transferring-a-repository))
> 
> 이렇게 여러 fork가 된 상태에서 ownership을 변경 했을 때 그게 유지 될지는 안해봐서 스터디 다 종료되고 transfer 하는게 덜 문제되지 않을까 생각을 해보았습니다
> 
> 아니면 간단하게 테스트용 저장소를 만들고 비슷하게 fork를 한다음에 ownership을 변경해보았을 때 어떻게 되는지 체크해 볼 수도 있을것 같아요 (private fork는 이전이 안된다고 하니 public fork는 될지도 모르겠네요 - If the transferred repository has any forks, then those forks will remain associated with the repository after the transfer is complete).

테스트 해봤는데 잘 되네요 (https://github.com/alps-jbnu/transfer-test)

Settings > Danger Zone > Transfer ownership > 옮길 user/org에 `alps-jbnu` 입력

CC. @Sabro98 @jinhongjung

**Comment by Sabro98** [comment]
아 감사합니다!

그럼 이번 주말에 바로 하는걸로 해야겠네요 👍

**Comment by jinhongjung** [comment]
@Sabro98 정리한 내용 확인 했습니다. 고생 많았습니다. PR 반영해주시고 issue close 해주세요~!
