### ISSUE TITLE
배열문제 3273번. occur배열 질문

### ISSUE THREAD

**Issue by tlstmdgjs** [alps-jbnu/22ALPStudy#47]
23번째줄 if문 occur역할이 뭔지모르겠어요.

[코드](https://github.com/tlstmdgjs/22ALPStudy/blob/master/Data_Structure/Code/tlstmdgjs/Array/3273.cpp)

**Comment by joonas-yoon** [comment]
https://github.com/tlstmdgjs/22ALPStudy/blob/master/Data_Structure/Code/tlstmdgjs/Array/3273.cpp#L23

**Comment by joonas-yoon** [comment]
@tlstmdgjs  "`x-a[i]` 가 이전에 등장한 적이 있는 가" 입니다.

배열 인덱스를 key로 사용해서 true/false로 메모했기 때문에, 배열 범위를 벗어나지 않도록 `x-a[i]` 가 0 또는 양수가 되도록 한 것입니다. 이 문제에서는 합쳐서 0이 나오지 않으므로 `x - a[i] > 0` 이어도 되겠네요.

```cpp
for (int i = 0; i < n; i++) {
  if (x-a[i] > 0 && occur[x - a[i]]) {
    freq++;
  }
  occur[a[i]] = true;
}
```
