### ISSUE TITLE
자료구조 스터디 질문

### ISSUE THREAD

**Issue by jinhongjung** [alps-jbnu/22ALPStudy#71]
@jys-jeong @AFpine @bootkorea @곽성대 (<-santam? 맞나요?)
매주 자료구조 관련 문제풀이를 진행하는 것 같은데 문제를 선별해서 진행하는 것인지 궁금합니다. 예를 들어서 몇 문제는 정해두고 멤버들이 다 푸는 방식으로 진행하는 것인가요? 문제를 미리 선별해서 진행하는 것이라면 선별되는 문제 목록도 같이 정리해주면 좋을 것 같습니다.

**Comment by jys-jeong** [comment]
저희 팀은 스터디 시간에 인원 3명 정도가 본인이 어려웠던 문제나 설명하고 싶은 문제를 풀이하는 방식으로 진행 하고 있습니다.

**Comment by Sabro98** [comment]
주제에 대한 문제는 Data_Structure -> README에 맨 아래 있는 **문제집** 을 참고해 푸는중입니다.

**Comment by bootkorea** [comment]
Group B의 진행 방식 또한 A 그룹과 동일하게 진행 중입니다.

@Sabro98 의 멘션에서 언급되었듯, 스터디 시작 전 1주 간 개념에 대한 이해와 문제풀이를 진행하였음을 전제로 스터디를 진행하고 있습니다.

'이해하지 못한 문제' '해결하지 못한 문제' '해결하였지만 풀이를 풀이를 공유하고 싶은 문제'
의 3가지 타입으로 분류하여 의견을 교류하고, 다른 풀이 방법에 대해서도 고민해보고 있습니다.

스터디 간 진행한 문제 등 기록을 Notion에 금주 안으로 정리하여 게시하겠습니다.

**Comment by jinhongjung** [comment]
@bootkorea @jys-jeong 
네 알겠습니다. 그럼 문제집에서 문제는 각자 개별적으로 선택해서 푸는 방향인가요? 아니면 문제집에 있는 모든 문제를 다 푸는 방향인가요?

**Comment by jinhongjung** [comment]
별개로 [[link](https://www.notion.so/2d13475d268a42a594deb5fcdd91d3be)]에 각자 올린 코드를 기준으로 progress를 체크해보았습니다. 각 스터디 매니저 분(@bootkorea @jys-jeong)들은 1, 2 주차 둘 다 업데이트가 안된 학생들은 업데이트를 독려해주길 바랍니다 (단순 copy & paste가 되면 안된다고 같이 이야기 해주세요). 2주 내로 업데이트가 되지 않는 경우는 해당 학생들 따로 미팅 요청해서 경위를 파악하겠습니다.

**Comment by bootkorea** [comment]
@jinhongjung 문제집 제작자의 의도대로 한 주에 모든 문제를 해결하는 것을 권장하고 있습니다.
그러나 무리하게 100% 완수를 해내는 것을 강요하지는 않고 있으며, 본인이 할 수 있는 만큼 진행하고 있습니다.
문제집에 수록된 문제의 난이도와 수를 매니저가 고려하여, 충분히 할 수 있는 양인지 체크하고 있으니,
강제성의 부재로 인해 멤버들이 대체로 나태해지는 일은 크게 걱정하지 않으셔도 됨을 자신할 수 있습니다.

업데이트가 제대로 이루어지지 않는 학생은 주기적으로 체크하여 함께 발전할 수 있도록 돕겠습니다!
Alps 동아리의 발전을 위해 지속적인 관심을 가져주셔서 감사합니다!

**Comment by jinhongjung** [comment]
@bootkorea 네 알겠습니다. 저희 동아리 특성상 실제 코딩을 하지 않으면 스터디를 하지 않는 것과 사실상 동일하다고 생각하기 때문에, 상황상 모든 문제를 풀지 못하더라도 서로 격려해서 최대한 많은 문제를 풀고 스터디/토론에 임할 수 있도록 해주세요. 저도 github 내용을 주기적으로 확인하니 멤버들에게 관련하여 이야기 전해주시고요~!
