### ISSUE TITLE
코테스터디 의견

### ISSUE THREAD

**Issue by jinhongjung** [alps-jbnu/22ALPStudy#72]
@Sabro98 

기업/대학원에서 어떤 절차와 어떤 종류의 문제로 코딩테스트를 진행하는지 웹 서베이도 같이 진행하시고 정리해서 공유하면 좋을 것 같습니다 (대표 기업/대학원 몇 개만 선별해서 진행하면 좋을 것 같습니다).

[[예시](https://4z7l.github.io/2021/09/28/2021_naver_recruit.html#:~:text=%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8%20%EC%A7%81%EC%A0%84%EC%97%90%20IDE,4%EB%AC%B8%EC%A0%9C%EB%A5%BC%20%ED%92%80%EC%96%B4%EC%95%BC%ED%96%88%EB%8B%A4.)]

**Comment by Sabro98** [comment]
각자 원하는 코딩테스트 몇 개 조사 후 다음주 스터디 까지 이 곳에 등록해두기로 하였습니다  👍

**Comment by copyrat90** [comment]
[(한 눈에 보는 표로 정리) 2016~2020 연도별 삼성전자, 카카오, 라인의 코딩 테스트 문제 유형 분석](https://www.hanbit.co.kr/channel/category/category_view.html?cms_code=CMS4385594264)

+ [삼성전자](https://tech-diary.tistory.com/30)
  + 오프라인으로 진행
  + 3시간, 2문제
  + 계산기, 메모장 사용 가능, 인터넷 검색 불가
  + **정답 여부 확인 불가**
  + 거의 항상 완전탐색, 시뮬레이션, 구현, BFS/DFS 문제만 나온다.\
    ([삼성 SW 역량테스트 기출문제](https://www.acmicpc.net/workbook/view/1152))
  + Visual Studio(`C/C++`), Eclipse(`Java`), PyCharm(`Python`) 사용 가능 (디버깅 가능)

+ [카카오](https://baek-kim-dev.site/261)
  + 프로그래머스에서 진행
  + 인터넷 검색 가능
  + 1차 코테: 알고리즘 위주
    + 5시간, 7문제
    + 유형이 크게 2개로 나뉘는 듯하다.
      1. 문자열, 시뮬레이션, 완전 탐색, 재귀, 이차원 배열 등 알고리즘보다 정확성이 중요한 유형
      2. 후반부 어려운 문제는 다양한 알고리즘(trie, 트리, DP, 그래프 등)
  + 2차 코테: 실무 비슷한 상황에서 가장 최적화된 솔루션을 찾아가기(?)
    > 탄탄한 기본기와 개발 경험을 바탕으로 문제의 요구 사항을 잘 이해하고, trade-off를 감안하여 로직을 설계하고 결과를 시뮬레이션을 통해 확인하면서 최선의 결과가 나오도록 점진적으로 로직을 개선해 나가는 역량을 검증 ([21 카카오 2차 공식 해설에서 발췌](https://tech.kakao.com/2021/02/16/2021-kakao-recruitment-round-2/))
    + 5시간, 1문제
    + Pass Fail 이 아니라, 각 문제별로 최적화가 더 잘 된 답안이 점수를 높게 받는 식.
    + 입출력을 카카오 서버 API 에 HTTP Request 보내서 한다.\
        JSON 다루는 데 익숙해야 할 듯.

+ [네이버](https://henrynoh.tistory.com/79)
  + 프로그래머스에서 진행
  + 2시간, 3~4문제
  + 인터넷 검색 불가 (레퍼런스 사이트는 허용)
  + **정답 여부 확인 불가**

* * *
### 기타
+ [문자열 문제가 점점 늘어나고 있다.](https://velog.io/@kimjaeseop/2021.03-%EB%9D%BC%EC%9D%B8-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%9B%84%EA%B8%B0)
  + 코테용으로는 문자열 처리가 까다로운 C/C++ 보다\
    Python 을 고려하는 게 좋아보인다.
+ 삼성 기출, 카카오 기출은 각각 [백준](https://www.acmicpc.net/workbook/view/1152)과 [프로그래머스](https://programmers.co.kr/learn/challenges)에서 풀어볼 수 있으니,\
  기출 문제로 실제 시험 시간에 맞춰서 풀어보는 연습 하면 좋을듯하다.

**Comment by jihyeonhur** [comment]
### 카이스트 전산학부 대학원 코딩테스트
[모집 요강](https://cs.kaist.ac.kr/content?menu=41) 

###  테스트 환경

**플랫폼**
   - 2018학년도 까지는 [Codility](https://app.codility.com/demo/take-sample-test/) 사용
   - 2019학년도, 2020학년도 모집때는 [Programmers](https://programmers.co.kr/learn/challenges) 사용   

**사용 가능 언어, IDE** 
   - C, C++, Python3, Java, JavaScript 사용 가능
   - Visual Studio(`C, C++`), PyCharm(`Python`), Intellij(`Java`), WebStorm(`JavaScript`) 사용 가능
   - 각 언어마다 공식 레퍼런스 사이트 참고 가능 &rarr; 함수 검색 가능
   
**주의 사항**
   - 시험 전 자신이 사용할 IDE 제대로 동작하는 지 반드시 확인하기 ("Hello World" 출력해보기)
   - Pycharm의 경우, 인터프리터 바인딩 잘 되었는지 확인 (버전 확인)

**기타**
   - 프로그래머스에서 코드 여러번 실행 가능, 코드 제출 여러번 할 수 있음
   - 채점 결과 바로 보여줌
   - 성능 테스트도 있기 때문에 시간 복잡도 계산도 해야함
   - 코로나 19로 인한 비대면 면접 실시로 2020년 가을 입시부터 코딩테스트 실시하지 않음 (앞으로는 어떻게 될지 모르는 듯?)
   


### 문제 유형

   - 45분 동안 3개의 문제   
   - 난이도 beginner 2문제, intermediate 1문제   
   - 영어 문제 있음   
   - 3문제 중 한 문제 빼고 난이도 어렵지 않은 듯   
   - 2019학년도 모집 때 intermediate dp 문제였음   
   - python 사용하는 것이 좋을 것으로 판단    

[참고후기](https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=frankjune&logNo=221347724550)

**Comment by jinhongjung** [comment]
조사하시느라 고생많으셨습니다~!

@Sabro98 조사한 내용 동아리 구성원에게 모두 공유될 수 있도록 안내 한번만 부탁드리겠습니다.
