### ISSUE TITLE
3/30 자구 B그룹 공유할 문제 조사

### ISSUE THREAD

**Issue by bootkorea** [alps-jbnu/22ALPStudy#93]
금주 해결할 문제의 양이 많아, 효율적인 스터디 진행을 위해 필요한 내용을 조사하려 합니다.

3/29 18:00까지 풀어보시고, 그 이후부터 올려주시면 되겠습니다.
'풀어보았지만 끝까지 해결하지 못한 문제' 를 적어주시고, 이후 본인의 풀이 방법을 공유하고자 하는 분은 '좋아요'를 남겨주시면 되겠습니다.

@zs0057 @JC-arl @tjdeo1102 @vuswltmd

**Comment by bootkorea** [comment]
ex) 1926 그림

**Comment by zs0057** [comment]
4179 불!  문제에대해 같이 논의해보고싶은 것이 있습니다.

**Comment by bootkorea** [comment]
2468 안전 영역
예제 정답대로 출력은 되는데 왜 안 나오는 지 토의해보고 싶네요

**Comment by Sabro98** [comment]
스터디 중 아래에 해당되는 부분들은 여기에서 추가적으로 토의해봐도 좋을 것 같네요

- 공유하면 좋을 것 같은 정보
- 토의를 했지만, 해결되지 못한 (또는 계속해서 애매한) 부분
- 기타 등등
